feat: Добавить основную часть дипломного проекта
ZaharovaLudmila/java-explore-with-me pull request #1
Opened 2022-10-31 18:28 UTC by ZaharovaLudmila

2022-11-01 18:32 UTC, db-exp requested changes

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/ExploreWithMeService.java
> +@SpringBootApplication(scanBasePackages = {"ru.practicum.ewmServer", "ru.practicum.statClient"})
Аннотация @SpringBootApplication включает в себя автоскан https://docs.spring.io/spring-boot/docs/2.0.x/reference/html/using-boot-using-springbootapplication-annotation.html и базовый пакет ru.practicum.ewmServer он по умолчанию просканирует

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/controller/category/CategoryAdminController.java
> +    public String test() {
Точно нужен?

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/exception/ConditionException.java
> +public class ConditionException extends IllegalArgumentException {
Можно просто RuntimeException

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/exception/NotFoundException.java
> +public class NotFoundException extends IllegalStateException {
тут прям точно RuntimeException )

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/exception/ErrorHandler.java
> +public class ErrorHandler {
Не хватает Forbidden 403 в случаях, когда пользователь редактирует чужую задачу итп

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/Category.java
> +    @Column(name = "category_name", nullable = false)
Добавь, пожалуйста, валидацию Size

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/Compilation.java
> +    private String title;
Добавь, пожалуйста, валидацию Size

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/Event.java
> +public class Event {
Добавь, пожалуйста, валидацию Size на String поля

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/Category.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/Event.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/Location.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/Request.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/User.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/User.java
> +public class User {
Добавь, пожалуйста, валидацию Size для String полей

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/AdminUpdateEventRequest.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/CategoryDto.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/CompilationDto.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/EventFullDto.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/EventShortDto.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/LocationDto.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/NewCategoryDto.java
> +    private String name;
Хорошо бы еще валидацию Size добавить

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/NewCategoryDto.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/NewCompilationDto.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/NewEventDto.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/NewEventDto.java
> +public class NewEventDto {
Добавь, пожалуйста, валидацию Size для String полей

2022-11-01 18:32 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewmStat/service/ParametersStat.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewmStat/service/ParametersStat.java
> +    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
можно static final

2022-11-01 18:32 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewmStat/repository/StatRepository.java
> +public interface StatRepository extends JpaRepository<EndpointHit, Long>  {
Добавь, пожалуйста, аннотацию Repository

2022-11-01 18:32 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewmStat/model/dto/ViewsStats.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewmStat/model/dto/EndpointHitDto.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewmStat/model/EndpointHit.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewmStat/model/EndpointHit.java
> +public class EndpointHit {
Добавь, пожалуйста, валидации Size, null или не null или blank на String поля

2022-11-01 18:32 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewmStat/controller/StatController.java
> +    public EndpointHitDto saveHit(@RequestBody EndpointHitDto endpointHitDto) {
Можно добавить Valid

2022-11-01 18:32 UTC, db-exp commented on stat-client/src/main/java/ru/practicum/statClient/dto/ViewsStats.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on stat-client/src/main/java/ru/practicum/statClient/dto/EndpointHitDto.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on stat-client/src/main/java/ru/practicum/statClient/StatClient.java
> +            urisString.append("uris=").append(uri).append("&");
с учетом ограничения на длину get запроса, тут можно просто через "+"

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/service/StatClientService.java
> +    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
можно static final

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Добавь, пожалуйста, аннотацию Repository

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/repository/RequestRepository.java
> +public interface RequestRepository extends JpaRepository<Request, Long> {
Добавь, пожалуйста, аннотацию Repository

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/repository/LocationRepository.java
> +public interface LocationRepository extends JpaRepository<Location, Long> {
Добавь, пожалуйста, аннотацию Repository

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/repository/EventRepository.java
> +public interface EventRepository extends JpaRepository<Event, Long> {
Добавь, пожалуйста, аннотацию Repository

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/repository/CompilationRepository.java
> +public interface CompilationRepository extends JpaRepository<Compilation, Long> {
Добавь, пожалуйста, аннотацию Repository

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/repository/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long> {
Добавь, пожалуйста, аннотацию Repository

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/parametrs/EventsPublicFindParams.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/parametrs/EventsAdminFindParams.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/parametrs/EventsAdminFindParams.java
> +    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Так как везде один формат, то можно вынести его в класс с константами и везде использовать

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/UserShortDto.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/UserDto.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/NewUserRequest.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/NewUserRequest.java
> +public class NewUserRequest {
Добавь, пожалуйста, Size для String полей

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/UpdateEventRequest.java
> +@Data
В рамках диплома нельзя пользоваться equals и hashcode, созданных аннотацией Data
Если необходимо, можно сделать Getter, Setter, ToString отдельно

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/UpdateEventRequest.java
> +public class UpdateEventRequest {
Добавь, пожалуйста, Size, null/не null или blank на String  поля

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/service/EventServiceImpl.java
> +            throw new ConditionException(String.format("User id = %d is not the initiator of the event id = %d",
вот тут по факту проверка прав - Forbidden 403

2022-11-01 18:32 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/service/RequestServiceImpl.java
> +            throw new ConditionException(String.format("User id = %d is not the initiator of the event id = %d",
Forbidden

2022-11-02 19:07 UTC, ZaharovaLudmila commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/UpdateEventRequest.java
> +public class UpdateEventRequest {
Я не стала добавлять изначально NotNull или NotBlank, потому что не все поля обязательные, по спецификации обязательно было только поле id. Какие-то поля могут не прийти на обновление, если я правильно поняла

2022-11-02 19:07 UTC, ZaharovaLudmila commented on stat-client/src/main/java/ru/practicum/statClient/StatClient.java
> +            urisString.append("uris=").append(uri).append("&");
Нам так предложил наставник на Q&A. Я правильно поняла, что нужно переписать так:
String urisString ;
        for (String uri : uris) {
            urisString = urisString +"uris="+uri+"&";
        }.
Пока не сделала, но если надо, сделаю)))

2022-11-02 19:40 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/model/dto/UpdateEventRequest.java
> +public class UpdateEventRequest {
не обязательно помечать NotNull, NotBlank, можно наоборот nullable=true проставить явно. Явное лучше неявного :)

2022-11-02 19:42 UTC, db-exp commented on stat-client/src/main/java/ru/practicum/statClient/StatClient.java
> +            urisString.append("uris=").append(uri).append("&");
StringBuilder тут не хорошо и не плохо - просто смысла особо в нем нет в текущем контексте )
можно ничего не делать там, где я пометил "можно"

2022-11-04 15:12 UTC, ZaharovaLudmila commented on main-service/src/main/java/ru/practicum/ewmServer/ExploreWithMeService.java
> +@SpringBootApplication(scanBasePackages = {"ru.practicum.ewmServer", "ru.practicum.statClient"})
Еще вопрос по этому моменту, если можно =) У меня пакеты назывались по-разному, сейчас я их обозвала одинаково и удалила scanBasePackages  вообще, если я оставляю @SpringBootApplication(scanBasePackages = {"ru.practicum.statClient"}) у меня не работают запросы на эндпоинты через Postman. Как в таком случае это должно работать? Если я удаляю пакет "ru.practicum.ewmServer" из скана.

2022-11-04 17:36 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/ExploreWithMeService.java
> +@SpringBootApplication(scanBasePackages = {"ru.practicum.ewmServer", "ru.practicum.statClient"})
можно оставить ru.practicum.statClient, я имел ввиду базовый убрать, он и так его просканирует

2022-11-04 17:39 UTC, ZaharovaLudmila commented on main-service/src/main/java/ru/practicum/ewmServer/ExploreWithMeService.java
> +@SpringBootApplication(scanBasePackages = {"ru.practicum.ewmServer", "ru.practicum.statClient"})
да, я поняла, что базовый убрать, но если я его убираю и оставляю так @SpringBootApplication(scanBasePackages = {"ru.practicum.statClient"}) у меня не работают запросы на эндпоинты через Postman, мне постман выводит ошибку, что такого пути нет, что типа такого : {
    "timestamp": "2022-10-23T13:45:15.425+00:00",
    "status": 404,
    "error": "Not Found",
    "path": "/events"
}

2022-11-04 17:50 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmServer/ExploreWithMeService.java
> +@SpringBootApplication(scanBasePackages = {"ru.practicum.ewmServer", "ru.practicum.statClient"})
Понял, можно так добавить под SpringBoot
@ComponentScan("ru.practicum")

2022-11-04 18:13 UTC, ZaharovaLudmila commented on main-service/src/main/java/ru/practicum/ewmServer/ExploreWithMeService.java
> +@SpringBootApplication(scanBasePackages = {"ru.practicum.ewmServer", "ru.practicum.statClient"})
Спасибо, так и сделаю)

2022-11-05 17:31 UTC, db-exp requested changes

2022-11-05 17:31 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmService/model/dto/UpdateEventRequest.java
> +    @Nullable
import org.springframework.lang.Nullable не нужен в этом случае - Size без NotNull/NotBlank по факту null пропустит, а если не null - будет проверять длину

2022-11-05 17:31 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmService/service/EventServiceImpl.java
> +    public EventFullDto publicGetEventById(long eventId, HttpServletRequest request) {
давай  вместо request передавать параметры из него, а то получается "протекание" слоев кода, request - слой контроллера

2022-11-05 17:31 UTC, db-exp commented on main-service/src/main/java/ru/practicum/ewmService/parametrs/EventsPublicFindParams.java
> +                                  HttpServletRequest request)
Вместо request давай передавать конкретные данные из него

2022-11-06 09:22 UTC, db-exp approved these changes

2022-11-06 10:35 UTC, merged